@startuml Reversi Class Diagram

Player *-- Human
Player *-- AIPlayer
AIPlayer *-- Game
AIPlayer *-- GameLogic
Game *-- Players
Game *-- Board
Game *-- GameLogic
GameConsoleView *-- Game
GameConsoleView *-- AIPlayer
BoardConsoleView *-- Board
BoardView *-- BoardConsoleView
GameConsoleView *-- BoardView
GUI_View *-- Game
GUI_View *-- BoardView
BrowserView *-- BoardView
BrowserView *-- Game
GameView *-- GameConsoleView
GameView *-- GUI_View
GameView *-- BrowserView    
GameController *-- BoardView
GameController *-- GameView

class Human {
    + symbol
    + colour
    + get_move()
}

class AIPlayer {
    + name
    + colour
    + get_move()
    + compile_next_moves()
    + calculate_move_scores()
}

class Player {
    + symbol
    + colour
}

class Players {
    + X
    + O
}

class Board {
    + size
    + matrix
    + get_cell(row, col)
    + update_cell(row, col)
    + update_board(row, col)
    + place_starting_pieces(player1, player2)
}

class Game {
     + change_player()
     + sum_player_pts()
     + check_winner()
     + record_winner()
}

class GameLogic {
     + is_valid_move()
     + make_move()
}

abstract class GameView {
    + get_opponent_type()
    + get_human_name()
    + draw_board()
    + display_winner()
    + display_score()
}

class GameConsoleView {
    + get_opponent_type()
    + get_human_name()
    + draw_board()
    + display_winner()
    + display_score()
}

abstract class BoardView {
    + board
    + draw_board()
}

class BoardConsoleView {
    + board
    + draw_board()
}

class GUI_View {}

class BrowserView {}

class GameController {
    + model
    + view
    + run_game()
}

@enduml